### ISSUE TITLE
Request permissions again

### ISSUE THREAD

**Issue by NoelDeMartin** [inrupt/solid-client-authn-js#1348]
I have realized that some users who are getting started with Solid often uncheck some permissions on the authorization screen. I think this is natural, because they are just getting started with Solid and they may be suspicious of an application (or maybe they are just tinkering to see what happens).

The problem is that once this happens, they are stuck on the application and can't do anything without updating the permissions on their POD. Depending on the UX of their provider, this can be a difficult task.

I wonder if it would be possible to use this library to re-request authorization, so that I could add a button in my app to restart the authorization process.

**Comment by NSeydoux** [comment]
Hi Noel !
Correct me if I'm wrong, but I think you are talking here specifically about the NSS "Trusted apps" screen, where you can check boxes to give Read, Write, Append and Control permission to the app, right ? If so, the issue is this mechanism isn't really standard-compliant, and it is being replaced in the spec by a client access control mechanism based on Client WebIDs as described in [Solid-OIDC](https://solid.github.io/authentication-panel/solid-oidc/#clientids-webid). Therefore, I'm not sure how much support we'll have for the legacy mechanism implemented by NSS.

I'm not 100% familiar with how this works, but in my understanding, the result of the authorization is recorded in the users's profile, with triples such as: 
```
#me acl:trustedApp  [
  acl:mode acl:Append, acl:Read, acl:Write;
  acl:origin <https://noeldemartin.github.io>
]
```
This could mean that with proper access (at least write), your app could 
- ask for user consent and give itself additional access without relying on the Pod of Identity Provider
- remove itself from the list, which (I think) may prompt the user again

However, if the app does not have Write access, I don't think there is a way to do this without having the user use a third-party mechanism, e.g. the data browser provided by NSS,

Does this make sense, and does it align with your own experience ?

**Comment by NoelDeMartin** [comment]
I wasn't aware that this was NSS specific, but now that you mention it I've noticed that this doesn't happen on Inrupt PODs. I thought it was actually the other way around, because I think it makes sense to ask users for how much permissions they want to give. But I think this type of granularity is still a work in progress in the spec itself.

Ok, I'll reach out to the maintainers of NSS and see what I can do about it. In that case, I'm closing this issue and I'll reopen it if there's something that can be done here.

Thanks.
