### ISSUE TITLE
Prompt=none vs. refresh tokens

### ISSUE THREAD

**Issue by woutermont** [inrupt/solid-client-authn-js#1682]
Just a question out of curiosity: why does this library use silent (re)authentication (i.e. `prompt=none` authentication requests), rather than refresh token requests, to achieve persistence?

**Comment by NSeydoux** [comment]
It actually uses both :). There are two main cases when a session's access token can no longer be used to access private resources: 
- (A) when it reaches its expiration date
- (B) when the page is reloaded, and it is lost (because it is stored in memory)

For case (A), the refresh token flow is appropriate, because the refresh token that has been issued along the access token is still available. We even set up a timeout to use the refresh token preventively, so that the access token is refreshed prior expiration. This is implemented in particular [there](https://github.com/inrupt/solid-client-authn-js/blob/9bcd506f3b64ef9f9b274bba77452d1239a4cdf9/packages/core/src/authenticatedFetch/fetchFactory.ts#L177).

Case (B) is a bit trickier. For security reasons, neither the access token nor the refresh token are stored in the `localStorage` in order not to be available to any other script loaded from the same origin. This means that on page reload, both are lost, preventing in this case to rely on the refresh token flow. However, we can then try to use silent authentication in case the OIDC issuer still has a valid cookie: the user is redirected to the OIDC issuer, and instantly back to the client application, authenticated or not, without any interaction with the OIDC issuer. Keeping a reference to the OIDC issuer in `localStorage` isn't a security vulnerability, and this silent redirect basically re-kickstart a regular authentication process, with an incoming redirect including an authorization code. The client can then exchange this authorization code for access and refresh tokens in the regular fashion.

Does this answer the question ?

**Comment by woutermont** [comment]
Yes, thanks! I overlooked the case where refresh tokens are still used. Two follow-up questions:

- Why do you consider refresh tokens insecure, given the existence of service workers (which can retain encapsulated storage over browser refreshes)?
- Do you think refresh tokens will be abandoned altogether, given the direction of the authentication panel to move away from Solid-OIDC access tokens towards local authorization servers?

**Comment by NSeydoux** [comment]
- I didn't mean to imply that refresh tokens aren't insecure by nature, it's just storing them in a shared storage that we want to avoid for security reasons, in order to prevent a third-party script to get access to it and to become able to issue its own access tokens. This is why both access and refresh tokens are only kept in the closure of the fetch function, where they cannot be read after the fetch function has been instantiated.
- It is early to say, but probably so, when the OIDC provider-issued access tokens are no longer the norm to access resources in a Solid Pod. In the meantime, retro-compatibility will be enforced, and refresh token will carry on being supported. Once we switch to a model where the ID token only is delivered by the Solid Identity Provider, and each resource server hints the client to an authorization server where they can authenticate, it will be up to each authorization server to manage the tokens, but even then refresh tokens could be used, as they are a fairly well-defined solution to the token lifespan-related issues. The purpose of the authentication and authorization panel in that regard is to reach a safe and modular architecture, while enabling a satisfactory user experience, and making sure it is possible to keep a session running on the long term is part of this user experience question.
