### ISSUE TITLE
Remove LDFlex/Comunica-specific workarounds from the source code

### ISSUE THREAD

**Issue by RubenVerborgh** [inrupt/solid-client-authn-js#176]
**Describe the bug**
https://github.com/inrupt/solid-auth-fetcher/pull/121#issuecomment-642101872

**Steps to solve**
- Does or doesn't LDflex-Comunica pass a correct `Headers` object?

**Comment by NSeydoux** [comment]
After some investigation, I'd say it does not. The `Headers` spec is the following: https://fetch.spec.whatwg.org/#headers-class, and in particular you'll notice that the interface is marked as `iterable`, which means (according to https://heycam.github.io/webidl/#dfn-value-pairs-to-iterate-over) that, among other methods, it should expose a `Symbol.iterator` in order to support structures such as `for...of`. 

It is not the case of the `Headers` object passed by `LDflex-Comunica`, as far as I can tell. It happens that it is the way `node-fetch` uses to look up the headers, which prompted the issue in the first place.

It really doesn't help that `lib.dom.d.ts` types also do their own thing that don't align with the spec either. i implemented an initial fix in #177, but even less workaround would be required if the `LDflex-Comunica` `Headers` object was an iterable.
