### ISSUE TITLE
Browser demoClientApp example no longer works

### ISSUE THREAD

**Issue by joachimvh** [inrupt/solid-client-authn-js#3182]
### Search terms you've used

demoClientApp

### Impacted package

Which packages do you think might be impacted by the bug ?

- [x] solid-client-authn-browser
- [ ] solid-client-authn-node
- [ ] solid-client-authn-core
- [ ] oidc-client-ext
- [ ] Other (please specify): ...

### Bug description

The client in `packages/browser/examples/demoClientApp` no longer seems to work. Building and starting seems to work correctly and gives the expected output similar to previous versions. But when browsing to `http://localhost:3001/` the result is a blank page with `Cannot GET /`. The browser console remains empty besides failing to load the favicon, and nothing new gets added to the process output.

The client still worked on v1.17.1 

### To Reproduce

1. `npm ci`
2. `cd packages/browser/examples/demoClientApp`
3. `npm start`

### Environment

* Windows 10
* v1.17.3 of the package.
* Node.js v18.18.0.

**Comment by NSeydoux** [comment]
Hi @joachimvh , thanks for reporting the issue. I'll look into it.

**Comment by NSeydoux** [comment]
If that helps, in the meantime, note that you can use https://github.com/inrupt/solid-client-authn-js/tree/main/packages/browser/examples/single/bundle, which has a very similar setup (React SPA)

**Comment by NSeydoux** [comment]
Actually, regarding this last point, I am considering removing `packages/browser/examples/demoClientApp` altogether, as it covers the same use case as `packages/browser/examples/single/bundle`, but with more "extra fluff" that makes it harder to make sense of the code, and that make it more brittle (case in point).

Since you noticed this demo was broken, I assume you are using it. Before I remove it, does it bring any value to you that isn't covered by `packages/browser/examples/single/bundle`?

**Comment by joachimvh** [comment]
I have no specific reason for using that one. I was just looking for a client to quickly test with in the past and that one fit the bill. The `single` example seems to fulfil the same role so that one is also fine for me.

**Comment by NSeydoux** [comment]
This example app has now been removed.
