### ISSUE TITLE
Bundle size is 1.01 Mib

### ISSUE THREAD

**Issue by jaxoncreed** [inrupt/solid-client-authn-js#41]
Ultimately this would be much lower (244KiB), here is the bundle makeup:

<img width="1395" alt="image" src="https://user-images.githubusercontent.com/5464743/80145809-c377c000-857e-11ea-97c8-731bb1f54349.png">

The largest problems are:
 - node-forge: a transient dependency of node-jose
 - node-jose: As far as I can tell, this is tree shaken as much as possible.
 - ajv: It might be possible to limit its size using ajv-cli https://www.npmjs.com/package/ajv-cli to precompile schemas.
 - lodash: There's only one lodash function used in my codebase, the rest is probably transient. This could be helped by https://github.com/lodash/lodash-webpack-plugin, but it's only compatible with `babel-loader` and we're using `ts-loader`
 - eliptic: a transient dependency of node-jose for generating eliptic curves

**Comment by nicolasmondada** [comment]
Bundle size has been reduced significantly since this issue was originally opened. This is an ongoing effort though and will continue in the future.
<img width="1244" alt="Screenshot 2022-05-05 at 13 12 43" src="https://user-images.githubusercontent.com/1138304/166920513-d5f56c62-87f8-4a0a-ad11-ab9cf6bb943f.png">
