### ISSUE TITLE
Access to https://pod.inrupt.com

### ISSUE THREAD

**Issue by SharonStrats** [inrupt/solid-client-authn-js#856]
Should anyone be able to create an account on the pod server above, which is listed in the documentation? I receive a 401 unauthorized error, with no way of logging in or creating an account.

**Comment by Vinnl** [comment]
Hi Sharon, creating an account can be done at signup.pod.inrupt.com. [These docs](https://docs.inrupt.com/developer-tools/javascript/client-libraries/tutorial/getting-started/) currently refer to [this page](https://docs.inrupt.com/pod-spaces/) that mentions that. @kay-kim - would it maybe make sense to link to it on the former page as well, or would that be too cluttered?

I've also internally asked the team responsible for pod.inrupt.com whether they could add a signup link from there, but I'm not sure if that's easy to do :)

**Comment by kay-kim** [comment]
Hey @Vinnl  - so.... by link to it on the "former page", do you mean the Getting Started page?   If so, I think we do if I'm understanding the request.  Apologies in advance if  I'm misunderstanding the  request.

<img width="739" alt="Screen Shot 2020-12-21 at 10 34 08 AM" src="https://user-images.githubusercontent.com/2126636/102793551-17d67800-4378-11eb-9e76-a226a0d5afd0.png">

**Comment by Vinnl** [comment]
@kay-kim Hum... Ehm yeah, that's what my guess was as to what page page Sharon was referring to with "listed in the documentation", but you're right, somehow I missed that link. Any other place you think it might be mentioned? Otherwise we'll just have to wait for Sharon to get back online (IIRC it's the middle of the night where she is right now) :)

**Comment by kay-kim** [comment]
Sounds good.
