### ISSUE TITLE
await session.logout() has no effect on session object

### ISSUE THREAD

**Issue by gibsonf1** [inrupt/solid-client-authn-js#894]
await session.logout() has no apparent effect on the session object itself but it does remove the ability to use the token.

As a work around, we are currently doing this:  session.info.isLoggedIn = false

Ideally, the logout would also hit the /.well-known/solid/logout  api on the app as the old solid-auth-client used to do, or is that option deprecated?

Thanks!

**Comment by NSeydoux** [comment]
Hi @gibsonf1 , and thanks for reporting this ! #909 should resolve the issue. 

Unfortunately, `/.well-known/solid/logout` isn't spec-compliant with OpenID connect, which is why `solid-client-authn-browser` does not have this feature. But basically (and correct me if I'm wrong), this endpoint ends the session of the current user against the Solid server (both Pod server and Identity Provider), regardless of the app you are using, right ? To make a parallel, it is as if logging out of Gitter also logged you out of Github, or am I mistaking ?

Anyways, handling a post-logout redirect is something that we consider. It would be very helpful if you described your logout use case :).

**Comment by NoelDeMartin** [comment]
I've also been wondering about this, because I noticed that `solid-auth-client` seems to log out from the idp as well, but this library doesn't (I'm not sure if `solid-auth-client` is calling `/.well-known/solid/logout` or what).

The use-case I've been thinking about is when I'm using someone else's computer, if I log into a Solid app and I logout, I wouldn't want that computer to be able to access that app again without introducing the password. And right now I'd have to visit the idp site manually (which, as user, I may not be familiar with because I was redirected to it during log in).

I agree with the simil with Github/Gitter, the difference I see is that Github is a standalone service and in the case of Solid apps it's possible that Solid apps is the only thing that users log into, and they may be unaware of the distinction. But yeah, I see the issues and I'm not sure what an authentication library should do by default.

In any case, it'd be nice to have the possibility to log out from the idp using this library as well, even if it's opt-in and not the default behaviour. That way, we could add something in the application's UI to configure it. For example, a check box saying "log out from idp as well" that is unchecked by default.

**Comment by erikhofer** [comment]
@NoelDeMartin thanks for fixing this! But what @NoelDeMartin says is still valid. Maybe open a new ticket for further discussion?

**Comment by NoelDeMartin** [comment]
@erikhofer I think you wanted to ping @NSeydoux on that first mention :)

@NSeydoux If you think what I'm saying makes sense, I can open an issue about adding opt-in configuration to log out from the identity provider. 

Something like:

```js
await session.logout({
    logoutIdp: true, // default to false
});
```

Although I have no idea how easy/difficult it is to implement that.

**Comment by erikhofer** [comment]
@NoelDeMartin Yes, thanks.

I wondering if logging out of the IDP is really our responsibility here. What if the user doesn't sign out manually in you scenario? In our app we can erase our key after some time, only write to session storage or not all. Isn't it the responsibility of the IDP to not log the user in permanently just for auth delegation?

**Comment by Vinnl** [comment]
Hi all, as a heads-up, a new release including this fix is pending and should be released shortly: https://github.com/inrupt/solid-client-authn-js/pull/911

As for logging out of the Solid Identity Provider: I don't think there is a ticket for that yet, so please do file an issue where we can gather use cases and :+1:'s independently of this issue. Unfortunately I don't think there's going to be an easy and clear-cut resolution though, unfortunately, as there are a lot of potential edge cases (which is why collecting use cases and real-world experience will be useful). Consider for example to sign in to forum.solidproject.org with your GitHub account - would you want that account to be logged out when you log out of the forum? Different people will probably provide different answers motivated by different use cases to that and similar questions, so it would be good to collect those.
