### ISSUE TITLE
session.handleIncomingRedirect logins but produces error 404 for https://<username>.inrupt.net/session

### ISSUE THREAD

**Issue by WhyINeedToFillUsername** [inrupt/solid-client-authn-js#981]
### Search terms you've used

request session

### Impacted package

Which packages do you think might be impacted by the bug ?

- [x] solid-client-authn-browser
- [ ] solid-client-authn-node
- [ ] solid-client-authn-core
- [ ] oidc-client-ext
- [ ] Other (please specify): ...

### Bug description

When I use solid-client-authn-browser to log in, using `session.handleIncomingRedirect(window.location.href)` successfully logins and then produces request to https://<username>.inrupt.net/session, which ends in 404:

![image](https://user-images.githubusercontent.com/9642545/105628576-003e5380-5e3e-11eb-9b53-d473867dba52.png)

(doesn't matter if I use await or not, I get the same error:
```
    await this.inruptService.session.handleIncomingRedirect(window.location.href);
```
or
```
    this.inruptService.session.handleIncomingRedirect(window.location.href)
      .then(sessionInfo => {
        this.webId = sessionInfo.webId;
        console.log(sessionInfo)
      }).finally(() => console.log("promise finished"));
```
)

Please note that this is an angular project, so the "initiator" only seems to be "zone-evergreen.js".

### To Reproduce
1. request login using `session.login`:
```
   await this.inruptService.session.login({
        oidcIssuer: this.oidcIssuer,
        redirectUrl: window.location.href,
      });
```
2. login to inrupt.net/solidcommunity.net
3. use `this.inruptService.session.handleIncomingRedirect` to handle the redirect
4. you get 404 error in console for a request to https://<username>.inrupt.net/session

### Expected result

no 404 error/no unsolicited request to inrupt.net/session

### Actual result

request to https://<username>.inrupt.net/session with 404 error

### Environment
Please run

  npx envinfo --system --npmPackages --binaries --npmGlobalPackages --browsers

in your project folder and paste the output here:

```
$ npx envinfo --system --npmPackages --binaries --npmGlobalPackages --browsers
npx: installed 1 in 1.314s

  System:
    OS: Windows 10 10.0.19041
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 16.11 GB / 31.71 GB
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.423.0), Chromium (88.0.705.50)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @angular-devkit/build-angular: ^0.1100.3 => 0.1100.7
    @angular/animations: ~11.0.3 => 11.0.9
    @angular/cdk: ^11.0.2 => 11.0.4
    @angular/cli: ~11.0.3 => 11.0.7
    @angular/common: ~11.0.3 => 11.0.9
    @angular/compiler: ~11.0.3 => 11.0.9
    @angular/compiler-cli: ~11.0.3 => 11.0.9
    @angular/core: ~11.0.3 => 11.0.9
    @angular/forms: ~11.0.3 => 11.0.9
    @angular/material: ^11.0.2 => 11.0.4
    @angular/platform-browser: ~11.0.3 => 11.0.9
    @angular/platform-browser-dynamic: ~11.0.3 => 11.0.9
    @angular/router: ~11.0.3 => 11.0.9
    @inrupt/solid-client: ^1.3.0 => 1.3.0
    @inrupt/solid-client-authn-browser: ^1.4.2 => 1.4.2
    @inrupt/vocab-common-rdf: ^0.7.2 => 0.7.2
    @types/jasmine: ~3.6.0 => 3.6.2
    @types/jasminewd2: ~2.0.3 => 2.0.8
    @types/node: ^12.11.1 => 12.19.14
    codelyzer: ^6.0.0 => 6.0.1
    crypto-browserify: ^3.12.0 => 3.12.0
    jasmine-core: ~3.6.0 => 3.6.0
    jasmine-spec-reporter: ~5.0.0 => 5.0.2
    karma: ~5.1.1 => 5.1.1
    karma-chrome-launcher: ~3.1.0 => 3.1.0
    karma-coverage-istanbul-reporter: ~3.0.2 => 3.0.3
    karma-jasmine: ~4.0.0 => 4.0.1
    karma-jasmine-html-reporter: ^1.5.0 => 1.5.4
    ngx-build-plus: ^10.1.1 => 10.1.1
    protractor: ~7.0.0 => 7.0.0
    rxjs: ~6.6.0 => 6.6.3
    stream-browserify: ^3.0.0 => 3.0.0
    ts-node: ~8.3.0 => 8.3.0
    tslib: ^2.0.0 => 2.1.0
    tslint: ~6.1.0 => 6.1.3
    typescript: ~4.0.2 => 4.0.5
    webpack: 5.10.0 => 5.10.0
    zone.js: ~0.10.2 => 0.10.3
  npmGlobalPackages:
    @angular/cli: 11.0.3
    http-server: 0.12.3
    npm: 6.14.11
    web-push: 3.4.4
    windows-build-tools: 5.2.2
    yarn-upgrade-all: 0.5.4
    yarn: 1.22.10

```

## Additional information

From my code, I have separated a minimal application that produces the error and also shows the exact way I am using the library:
https://github.com/WhyINeedToFillUsername/solid-error3
You can run it and test it yourself, see inrupt.component.ts:47 (https://github.com/WhyINeedToFillUsername/solid-error3/blob/master/src/app/components/inrupt/inrupt.component.ts#L47) for the problematic code.

**Comment by NSeydoux** [comment]
Hi @WhyINeedToFillUsername, thanks for reaching out. From version [1.4.0](https://github.com/inrupt/solid-client-authn-js/blob/master/CHANGELOG.md#140---2020-01-11), we added a feature to mitigate the issue that logs you out of your session when you refresh your page. It is a stopgap solution, that has known limitations that we intend to address in a cleaner, more permanent fix soon. In the meantime, we had to base session management on a server-side cookie, a feature which isn't implemented by all the Solid servers (or rather, that is only implemented by ESS, the server hosting https://pod.inrupt.com). Looking up this session endpoint is intentional, and getting a 404 is an indication to `solid-client-authn-browser` that the server doesn't implement the cookie-based session management we are looking for. This additional request will no longer be necessary once the long-term session management solution is implemented.

This explains the behaviour you are experiencing. Reading your bug report, I wasn't sure it has an adversary effect on your code (throwing an error, preventing a session from being authenticated against an NSS instance), or if the bug you report is this additional request, that the library (and not your application code) initiates, which is understandably confusing :). With this context in mind, do you think this issue can be closed (and I'll try to think updating it when the long-term solution is released so that you know when the additional request won't be fired anymore), or can you describe the failure you are experiencing at an applicative level ?

**Comment by WhyINeedToFillUsername** [comment]
Thank you for the answer.

I discovered this together with https://github.com/solid/community-server/issues/546. I thought something is wrong, as I couldn't login at all for one user and got these 404 errors for others. I wanted to make sure I'm not doing something wrong and wanted to understand what is going on with that request.

If you're saying this is a _feature, not a bug_, or rather an expected temporary behavior, and since it's not breaking my app, it is ok for me to close the bug :)

**Comment by NSeydoux** [comment]
Haha I never thought I'd be the "it's not a bug, it's a feature" person, and yet here I am :p. Thanks for following up, and I'll try to keep this updated when the definitive behaviour is in place.
